version: '2'

services:
        percona-xtradb-cluster:
          image: perconalab/percona-xtradb-cluster:latest
          environment:
            MYSQL_ROOT_PASSWORD: secret
            CLUSTER_NAME: test 
          networks:
            - test_net 
          ports:
            - "3306"
          volumes:
            # create volumes for use
            - /var/lib/mysql

networks:
  test_net:
    driver: overlay
