node_a:
    build: .
    expose:
    - 3306
    - 4444
    - 4567
    - 4568
    volumes:
    - /opt/nodeA/mysql/data:/var/lib/mysql

node_b:
    build: .
    expose:
    - 3306
    - 4444
    - 4567
    - 4568
    volumes:
    - /opt/nodeB/mysql/data:/var/lib/mysql

node_c:
    build: .
    expose:
    - 3306
    - 4444
    - 4567
    - 4568
    volumes:
    - /opt/nodeC/mysql/data:/var/lib/mysql

proxysql:
    build: proxysql/
    volumes:
    - /opt/proxysql/mysql/data:/var/lib/mysql
    links:
    - nodeA
    - nodeB
    - nodeC
    ports:
    - "2222:22"
    - "6032:6032"
    expose:
    - 22
    - 6032
